// Layout page for root node
import { Metadata } from "next"

export const metadata: Metadata = {
    // title metadata
    title: {
        default: "Learning Next.js",
        template: "%s | by DUDE69",
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: {
    children: React.ReactNode
}) {
    return (
        <html>
            <body>
                <header style={{
                    backgroundColor: 'lightblue',
                    padding: '1rem',
                }}>
                    <p>Header</p>
                </header>
                {children}
                <footer style={{
                    backgroundColor: 'ghostwhite',
                    padding: '1rem',
                }}>
                    <p>Footer</p>
                </footer>
            </body>
        </html >
    )
}